###
### .travis.yml
###

sudo: false
os: linux
dist: trusty
language: node_js
node_js: 'node'
before_install:
  - npm install -g npm@^5    # npm-6 dropped support for Node-4
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libnotify-bin; fi
stages:
  - lint # lint code and docs
  - test # all tests
jobs:
  include:
    - stage: lint
      script: npm run lint
      env:
        - NODE_ENV=development
      before_install: false
    - &test
      stage: test
      script: npm test
      env:
        - NODE_ENV=production
    - <<: *test
      os: osx
    - <<: *test
      node_js: '8'
    - <<: *test
      node_js: '8'
      os: osx
    - <<: *test
      node_js: '6'
    - <<: *test
      node_js: '6'
      os: osx
    - <<: *test
      node_js: '4'
    - <<: *test
      node_js: '4'
      os: osx

