###
### .travis.yml
###

sudo: false
os:
  - linux
  - osx
dist: trusty
language: node_js
node_js:
  - '4'
  - '6'
  - '8'
  - 'node'
env:
  - NODE_ENV=development
before_install:
  - npm install -g npm@5^
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libnotify-bin; fi
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm test
