###
### .travis.yml
###

sudo: false
os:
  - linux
  - osx
dist: trusty
language: node_js
node_js:
  - '4'
  - '6'
  - '8'
  - 'node'
env:
  - NODE_ENV=production
before_install:
  - npm install -g npm@^6
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libnotify-bin; fi
stages:
  - lint # lint code and docs
  - test # all tests
jobs:
  include:
    - stage: lint
      script: npm run lint
      env:
        - NODE_ENV=development
    - stage: test
      script: npm test
